create extension if not exists pgcrypto;

create table if not exists public.orders (
    id uuid primary key default gen_random_uuid(),
    order_number text unique not null,
    customer_name text not null,
    phone text not null,
    address text not null,
    notes text,
    payment_method text not null default 'cash',
    total numeric not null default 0 check (total >= 0),
    status text not null default 'new' check (status in ('new', 'accepted', 'preparing', 'delivering', 'delivered', 'cancelled')),
    created_at timestamptz not null default now()
);

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id uuid not null references public.orders(id) on delete cascade,
    product_name text not null,
    size text not null,
    quantity integer not null check (quantity between 1 and 20),
    unit_price numeric not null check (unit_price >= 0),
    total_price numeric not null check (total_price >= 0)
);

-- كتالوج المنتجات: المرجع الوحيد للأسعار. الموقع بيعرض القائمة منه مباشرة،
-- ودالة create_order بتسعّر الطلب منه بردو، فمفيش سعر بييجي من المتصفح كما هو.
-- علشان تغيّر سعر أو تضيف أو تشيل صنف بعد كده، عدّل الجدول ده من Table Editor
-- في Supabase (أو شغّل insert/update جديد) وهيتحدث في الموقع والطلبات فورًا.
create table if not exists public.products (
    id text primary key,
    category text not null,
    name text not null,
    variant_label text,
    description text,
    price numeric not null check (price >= 0),
    sort_order integer not null default 0,
    is_active boolean not null default true
);

alter table public.order_items add column if not exists product_id text references public.products(id);

create table if not exists public.admin_users (
    user_id uuid primary key references auth.users(id) on delete cascade
);

-- بعد إنشاء مستخدم المدير من Authentication > Users،
-- استبدل UUID التالي بمعرّف المستخدم وشغّل السطر:
-- insert into public.admin_users (user_id) values ('USER_UUID_HERE');
insert into public.admin_users (user_id)
values ('f4e58620-0a40-4a60-9e59-4f00785cc484')
on conflict (user_id) do nothing;

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.admin_users enable row level security;
alter table public.products enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.admin_users where user_id = auth.uid()
    );
$$;

revoke all on public.orders from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
revoke all on public.admin_users from anon, authenticated;
revoke all on public.products from anon, authenticated;
grant usage on schema public to anon, authenticated;
grant select, update on public.orders to authenticated;
grant select on public.order_items to authenticated;
grant select on public.products to anon, authenticated;

drop policy if exists "Anyone can create orders" on public.orders;
drop policy if exists "Anyone can create order items" on public.order_items;
drop policy if exists "Anyone can read orders" on public.orders;
drop policy if exists "Anyone can read order items" on public.order_items;
drop policy if exists "Anyone can update order status" on public.orders;
drop policy if exists "Admins can read orders" on public.orders;
drop policy if exists "Admins can read order items" on public.order_items;
drop policy if exists "Admins can update orders" on public.orders;
drop policy if exists "Anyone can read active products" on public.products;

create policy "Admins can read orders"
on public.orders for select to authenticated
using (public.is_admin());

create policy "Admins can read order items"
on public.order_items for select to authenticated
using (public.is_admin());

create policy "Admins can update orders"
on public.orders for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Anyone can read active products"
on public.products for select to anon, authenticated
using (is_active);

-- ================== قائمة كبابجي العربي ==================
insert into public.products (id, category, name, variant_label, description, price, sort_order, is_active) values
-- المشويات (بالوزن: ربع / نص / كيلو)
('grill-farkha-quarter', 'المشويات', 'فرخة مشوية علي الفحم', 'ربع', null, 90, 1010, true),
('grill-farkha-half', 'المشويات', 'فرخة مشوية علي الفحم', 'نص', null, 180, 1020, true),
('grill-farkha-kilo', 'المشويات', 'فرخة مشوية علي الفحم', 'كيلو', null, 250, 1030, true),
('grill-kofta-kandouz-quarter', 'المشويات', 'كفتة كندوز بلدي', 'ربع', null, 125, 1040, true),
('grill-kofta-kandouz-half', 'المشويات', 'كفتة كندوز بلدي', 'نص', null, 250, 1050, true),
('grill-kofta-kandouz-kilo', 'المشويات', 'كفتة كندوز بلدي', 'كيلو', null, 500, 1060, true),
('grill-kofta-dany-quarter', 'المشويات', 'كفتة ضاني', 'ربع', null, 150, 1070, true),
('grill-kofta-dany-half', 'المشويات', 'كفتة ضاني', 'نص', null, 350, 1080, true),
('grill-kofta-dany-kilo', 'المشويات', 'كفتة ضاني', 'كيلو', null, 600, 1090, true),
('grill-shish-tawook-quarter', 'المشويات', 'شيش طاووك', 'ربع', null, 125, 1100, true),
('grill-shish-tawook-half', 'المشويات', 'شيش طاووك', 'نص', null, 250, 1110, true),
('grill-shish-tawook-kilo', 'المشويات', 'شيش طاووك', 'كيلو', null, 500, 1120, true),
('grill-kebda-baladi-quarter', 'المشويات', 'كبدة بلدي', 'ربع', null, 125, 1130, true),
('grill-kebda-baladi-half', 'المشويات', 'كبدة بلدي', 'نص', null, 250, 1140, true),
('grill-kebda-baladi-kilo', 'المشويات', 'كبدة بلدي', 'كيلو', null, 500, 1150, true),
('grill-tarab-quarter', 'المشويات', 'طرب', 'ربع', null, 150, 1160, true),
('grill-tarab-half', 'المشويات', 'طرب', 'نص', null, 300, 1170, true),
('grill-tarab-kilo', 'المشويات', 'طرب', 'كيلو', null, 600, 1180, true),
('grill-sogo2-baladi-quarter', 'المشويات', 'سجق بلدي', 'ربع', null, 125, 1190, true),
('grill-sogo2-baladi-half', 'المشويات', 'سجق بلدي', 'نص', null, 250, 1200, true),
('grill-sogo2-baladi-kilo', 'المشويات', 'سجق بلدي', 'كيلو', null, 500, 1210, true),
('grill-resh-dany-quarter', 'المشويات', 'ريش ضاني', 'ربع', null, 175, 1220, true),
('grill-resh-dany-half', 'المشويات', 'ريش ضاني', 'نص', null, 350, 1230, true),
('grill-resh-dany-kilo', 'المشويات', 'ريش ضاني', 'كيلو', null, 700, 1240, true),
('grill-kabab-dany-quarter', 'المشويات', 'كباب ضاني', 'ربع', null, 200, 1250, true),
('grill-kabab-dany-half', 'المشويات', 'كباب ضاني', 'نص', null, 400, 1260, true),
('grill-kabab-dany-kilo', 'المشويات', 'كباب ضاني', 'كيلو', null, 800, 1270, true),
('grill-nifa-dany-quarter', 'المشويات', 'نيفة ضاني', 'ربع', null, 175, 1280, true),
('grill-nifa-dany-half', 'المشويات', 'نيفة ضاني', 'نص', null, 350, 1290, true),
('grill-nifa-dany-kilo', 'المشويات', 'نيفة ضاني', 'كيلو', null, 700, 1300, true),
-- الساخن
('hot-fatta-mozza', 'الساخن', 'فتة موزة ضاني', null, null, 250, 2010, true),
('hot-pigeon', 'الساخن', 'فرد حمام', null, null, 200, 2020, true),
('hot-mumbar', 'الساخن', 'ممبار', null, null, 100, 2030, true),
('hot-mahshi', 'الساخن', 'محاشي مشكل', null, null, 50, 2040, true),
('hot-molokhia', 'الساخن', 'ملوخية', null, null, 30, 2050, true),
('hot-rice-basmati', 'الساخن', 'أرز بسمتي', null, null, 40, 2060, true),
('hot-rice-khalta', 'الساخن', 'أرز بالخلطة', null, null, 50, 2070, true),
('hot-rice-shaeria', 'الساخن', 'أرز بالشعرية', null, null, 30, 2080, true),
-- الطواجن
('tagine-veg-meat', 'الطواجن', 'طاجن خضار مشكل باللحمة', null, null, 180, 3010, true),
('tagine-kawarea', 'الطواجن', 'طاجن كوارع', null, null, 170, 3020, true),
('tagine-akkawi-onion', 'الطواجن', 'طاجن عكاوي بالبصل', null, null, 160, 3030, true),
('tagine-lisan-asfour-meat', 'الطواجن', 'طاجن لسان عصفور باللحمة', null, null, 180, 3040, true),
('tagine-macarona-bechamel', 'الطواجن', 'طاجن مكرونة بشاميل', null, null, 80, 3050, true),
('tagine-rice-moamar', 'الطواجن', 'طاجن أرز معمر', null, null, 50, 3060, true),
('tagine-ra2ee2-meat', 'الطواجن', 'طاجن رقاق باللحمة', null, null, 100, 3070, true),
-- الوجبات
('meal-werk', 'الوجبات', 'وجبة ورك', null, 'أرز + خضار مشكل + بوم فريت + سلطات + عيش', 130, 4010, true),
('meal-sadr', 'الوجبات', 'وجبة صدر', null, 'أرز + خضار مشكل + بوم فريت + سلطات + عيش', 140, 4020, true),
('meal-kofta', 'الوجبات', 'وجبة كفتة', null, 'أرز + خضار مشكل + بوم فريت + سلطات + عيش', 160, 4030, true),
('meal-tarab', 'الوجبات', 'وجبة طرب', null, 'أرز + خضار مشكل + بوم فريت + سلطات + عيش', 200, 4040, true),
('meal-mix-grill', 'الوجبات', 'وجبة ميكس جريل', null, 'ربع ورك + ربع كفتة + أصابع كفتة + أرز + خضار مشكل + بوم فريت + سلطات + عيش', 200, 4050, true),
('meal-arabi', 'الوجبات', 'وجبة العربي', null, '2 أصابع كفتة + 2 شيش + سجق + كباب + أرز + خضار مشكل + بوم فريت + سلطات + عيش', 250, 4060, true),
-- السندوتشات (بنوع العيش: بلدي / فينو / سوري)
('sw-kofta-mashwia-baladi', 'السندوتشات', 'كفتة مشوية علي الفحم', 'بلدي', null, 45, 5010, true),
('sw-kofta-mashwia-fino', 'السندوتشات', 'كفتة مشوية علي الفحم', 'فينو', null, 35, 5020, true),
('sw-kofta-mashwia-sory', 'السندوتشات', 'كفتة مشوية علي الفحم', 'سوري', null, 25, 5030, true),
('sw-kebda-eskandarani-baladi', 'السندوتشات', 'كبدة إسكندراني', 'بلدي', null, 45, 5040, true),
('sw-kebda-eskandarani-fino', 'السندوتشات', 'كبدة إسكندراني', 'فينو', null, 35, 5050, true),
('sw-kebda-eskandarani-sory', 'السندوتشات', 'كبدة إسكندراني', 'سوري', null, 25, 5060, true),
('sw-kebda-balarda-baladi', 'السندوتشات', 'كبدة بالرده', 'بلدي', null, 50, 5070, true),
('sw-kebda-balarda-fino', 'السندوتشات', 'كبدة بالرده', 'فينو', null, 40, 5080, true),
('sw-kebda-balarda-sory', 'السندوتشات', 'كبدة بالرده', 'سوري', null, 30, 5090, true),
('sw-sogo2-eskandarani-baladi', 'السندوتشات', 'سجق إسكندراني', 'بلدي', null, 45, 5100, true),
('sw-sogo2-eskandarani-fino', 'السندوتشات', 'سجق إسكندراني', 'فينو', null, 35, 5110, true),
('sw-sogo2-eskandarani-sory', 'السندوتشات', 'سجق إسكندراني', 'سوري', null, 25, 5120, true),
('sw-sogo2-fahm-baladi', 'السندوتشات', 'سجق علي الفحم', 'بلدي', null, 45, 5130, true),
('sw-sogo2-fahm-fino', 'السندوتشات', 'سجق علي الفحم', 'فينو', null, 35, 5140, true),
('sw-sogo2-fahm-sory', 'السندوتشات', 'سجق علي الفحم', 'سوري', null, 25, 5150, true),
('sw-shish-tawook-baladi', 'السندوتشات', 'شيش طاووك علي الفحم', 'بلدي', null, 55, 5160, true),
('sw-shish-tawook-fino', 'السندوتشات', 'شيش طاووك علي الفحم', 'فينو', null, 45, 5170, true),
('sw-shish-tawook-sory', 'السندوتشات', 'شيش طاووك علي الفحم', 'سوري', null, 35, 5180, true),
('sw-tarab-dany-baladi', 'السندوتشات', 'طرب ضاني علي الفحم', 'بلدي', null, 65, 5190, true),
('sw-tarab-dany-fino', 'السندوتشات', 'طرب ضاني علي الفحم', 'فينو', null, 55, 5200, true),
('sw-tarab-dany-sory', 'السندوتشات', 'طرب ضاني علي الفحم', 'سوري', null, 45, 5210, true),
('sw-kabab-dany-baladi', 'السندوتشات', 'كباب ضاني علي الفحم', 'بلدي', null, 75, 5220, true),
('sw-kabab-dany-fino', 'السندوتشات', 'كباب ضاني علي الفحم', 'فينو', null, 65, 5230, true),
('sw-kabab-dany-sory', 'السندوتشات', 'كباب ضاني علي الفحم', 'سوري', null, 55, 5240, true),
('sw-kabab-kandouz-baladi', 'السندوتشات', 'كباب كندوز علي الفحم', 'بلدي', null, 70, 5250, true),
('sw-kabab-kandouz-fino', 'السندوتشات', 'كباب كندوز علي الفحم', 'فينو', null, 60, 5260, true),
('sw-kabab-kandouz-sory', 'السندوتشات', 'كباب كندوز علي الفحم', 'سوري', null, 50, 5270, true),
('sw-zinger-baladi', 'السندوتشات', 'زنجر حار', 'بلدي', null, 60, 5280, true),
('sw-zinger-fino', 'السندوتشات', 'زنجر حار', 'فينو', null, 50, 5290, true),
('sw-bania-baladi', 'السندوتشات', 'بانيه', 'بلدي', null, 55, 5300, true),
('sw-bania-fino', 'السندوتشات', 'بانيه', 'فينو', null, 45, 5310, true),
('sw-pomfrit-baladi', 'السندوتشات', 'بوم فريت', 'بلدي', null, 40, 5320, true),
('sw-pomfrit-fino', 'السندوتشات', 'بوم فريت', 'فينو', null, 30, 5330, true),
('hawawshi-fahm', 'السندوتشات', 'حواوشي علي الفحم', null, null, 25, 5340, true),
('hawawshi-eskandarani', 'السندوتشات', 'حواوشي فرن إسكندراني', null, null, 35, 5350, true),
('hawawshi-mozzarella', 'السندوتشات', 'حواوشي موزريلا', null, null, 45, 5360, true),
('burger-arabi', 'السندوتشات', 'هامبرجر العربي', null, null, 70, 5370, true),
('fries-pack', 'السندوتشات', 'باكت بوم فريت', null, null, 20, 5380, true),
-- الصواني (تُقدَّم مع عيش وشطة)
('tray-sahab', 'الصواني', 'صينية الصحاب', null, 'ربع كفتة + ربع شيش طاووك + ربع سجق + ربع نيفة + كيلو أرز بسمتي بالمكسرات', 800, 6010, true),
('tray-eila', 'الصواني', 'صينية العيلة', null, 'نص فرخة مشوية + ربع كفتة مشوية + ربع نيفة + 2 حمام + ربع ممبار + كيلو أرز بسمتي بالمكسرات', 1000, 6020, true),
('tray-walima', 'الصواني', 'صينية الوليمة', null, 'فرخة مشوية + نص كفتة + ربع سجق + 2 حمام + ربع ممبار + نيفة + 2 كيلو أرز بسمتي بالمكسرات', 1500, 6030, true),
-- السلطات
('salad-dakous', 'السلطات', 'سلطة دقوس', null, null, 20, 7010, true),
('salad-coleslaw', 'السلطات', 'سلطة كول سلو', null, null, 20, 7020, true),
('salad-tomeya', 'السلطات', 'سلطة تومية', null, null, 20, 7030, true),
('salad-tahina', 'السلطات', 'سلطة طحينة', null, null, 10, 7040, true),
('salad-babaghanoug', 'السلطات', 'سلطة بابا غنوج', null, null, 20, 7050, true),
('salad-green', 'السلطات', 'سلطة خضراء', null, null, 10, 7060, true),
('salad-tomato', 'السلطات', 'سلطة طماطم متبلة', null, null, 10, 7070, true),
('salad-eggplant-pickle', 'السلطات', 'سلطة بتنجان مخلل', null, null, 10, 7080, true),
-- الشوربة
('soup-lisan-asfour', 'الشوربة', 'شوربة لسان عصفور', null, null, 30, 8010, true),
('soup-kawarea', 'الشوربة', 'شوربة كوارع', null, null, 50, 8020, true),
('soup-baharez', 'الشوربة', 'شوربة بهاريز', null, null, 70, 8030, true),
-- الحلو
('dessert-rice-pudding', 'الحلو', 'أرز باللبن', null, null, 20, 9010, true),
('dessert-om-ali', 'الحلو', 'أم علي', null, null, 30, 9020, true),
('dessert-jelly', 'الحلو', 'جيلي', null, null, 20, 9030, true),
('dessert-custard', 'الحلو', 'كاستر', null, null, 20, 9040, true),
-- المشروبات
('drink-water-small', 'المشروبات', 'مياه معدنية صغيرة', null, null, 5, 10010, true),
('drink-water-large', 'المشروبات', 'مياه معدنية كبيرة', null, null, 10, 10020, true),
('drink-can', 'المشروبات', 'كانز', null, null, 20, 10030, true),
('drink-arabi', 'المشروبات', 'مشروب العربي', null, null, 30, 10040, true),
('drink-karkade', 'المشروبات', 'كركديه', null, null, 20, 10050, true),
('drink-mango', 'المشروبات', 'مانجو', null, null, 30, 10060, true)
on conflict (id) do update set
    category = excluded.category,
    name = excluded.name,
    variant_label = excluded.variant_label,
    description = excluded.description,
    price = excluded.price,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active;

-- ================== طلبات: مسعّرة بالكامل من الجدول أعلاه ==================
-- الشكل الجديد: items_data بقت مجرد [{product_id, quantity}, ...]
-- بدون اسم أو سعر جاي من المتصفح؛ الدالة نفسها بتجيب الاسم والسعر من
-- public.products، فمفيش طريقة حد يغيّر سعر صنف من الـ devtools ويأثر على الطلب.
-- رقم الطلب كمان بقى بيتولّد من sequence في قاعدة البيانات فمش ممكن يتكرر.
create sequence if not exists public.order_number_seq;

drop function if exists public.create_order(jsonb, jsonb);

create or replace function public.create_order(order_data jsonb, items_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    new_order_id uuid := gen_random_uuid();
    generated_number text;
    computed_total numeric := 0;
    item jsonb;
    product record;
    quantity integer;
    line_total numeric;
begin
    if items_data is null or jsonb_array_length(items_data) = 0 then
        raise exception 'Order must contain at least one item';
    end if;

    generated_number := 'ORD-' || to_char(now(), 'YYYYMMDD') || '-'
        || lpad(nextval('public.order_number_seq')::text, 4, '0');

    insert into public.orders (
        id, order_number, customer_name, phone, address, notes, payment_method, total, status
    ) values (
        new_order_id,
        generated_number,
        left(trim(order_data->>'customer_name'), 120),
        left(trim(order_data->>'phone'), 40),
        left(trim(order_data->>'address'), 500),
        left(coalesce(order_data->>'notes', ''), 1000),
        case when order_data->>'payment_method' = 'transfer' then 'transfer' else 'cash' end,
        0,
        'new'
    );

    for item in select * from jsonb_array_elements(items_data)
    loop
        select p.* into product
        from public.products p
        where p.id = item->>'product_id' and p.is_active
        limit 1;

        if not found then
            raise exception 'Unknown or unavailable product: %', item->>'product_id';
        end if;

        quantity := least(greatest(coalesce((item->>'quantity')::integer, 1), 1), 20);
        line_total := product.price * quantity;
        computed_total := computed_total + line_total;

        insert into public.order_items (
            order_id, product_id, product_name, size, quantity, unit_price, total_price
        ) values (
            new_order_id,
            product.id,
            product.name,
            coalesce(product.variant_label, ''),
            quantity,
            product.price,
            line_total
        );
    end loop;

    update public.orders set total = computed_total where id = new_order_id;

    return jsonb_build_object('id', new_order_id, 'order_number', generated_number);
end;
$$;

grant execute on function public.create_order(jsonb, jsonb) to anon, authenticated;
